AppBundle\Entity\Campaign:
    type: entity
    table: campaign
    repositoryClass: AppBundle\Repository\CampaignRepository
    gedmo:
        translation:
            locale: locale
    manyToOne:
        cycle:
            targetEntity: Cycle
            inversedBy: campaigns
            joinColumn:
                name: cycle_id
                referencedColumnName: id
    oneToMany:
        scenarios:
            targetEntity: Scenario
            orderBy: {'id':'ASC'}
            mappedBy: campaign
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
        size:
            type: smallint
            nullable: false

    uniqueConstraints:
        campaign_code_idx:
            columns: [ code ]
                    