AppBundle\Entity\Card:
    type: entity
    table: card
    repositoryClass: AppBundle\Repository\CardRepository
    gedmo:
        translation:
            locale: locale
    manyToOne:
        pack:
            targetEntity: Pack
            inversedBy: cards
            joinColumn:
                name: pack_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        subtype:
            targetEntity: Subtype
            inversedBy: cards
            joinColumn:
                name: subtype_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            joinColumn:
                name: faction_id
                referencedColumnName: id
        encounter:
            targetEntity: Encounter
            inversedBy: cards
            joinColumn:
                name: encounter_id
                referencedColumnName: id
    oneToMany:
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        position:
            type: smallint
            nullable: false
        encounterPosition:
            type: smallint
            nullable: true
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
        subname:
            type: string
            length: 1024
            nullable: true
            gedmo:
                - translatable
        cost:
            type: smallint
            nullable: true
        text:
            type: text
            nullable: true
            gedmo:
                - translatable
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        quantity:
            type: smallint
            nullable: false
        skillWillpower:
            type: smallint
            nullable: true
        skillIntellect:
            type: smallint
            nullable: true
        skillCombat:
            type: smallint
            nullable: true
        skillAgility:
            type: smallint
            nullable: true
        skillWild:
            type: smallint
            nullable: true
        xp:
            type: smallint
            nullable: true
        shroud:
            type: smallint
            nullable: true
        clues:
            type: smallint
            nullable: true
        doom:
            type: smallint
            nullable: true
        health:
            type: smallint
            nullable: true
        sanity:
            type: smallint
            nullable: true
        enemyDamage:
            type: smallint
            nullable: true
        enemyHorror:
            type: smallint
            nullable: true
        enemyFight:
            type: smallint
            nullable: true
        enemyEvade:
            type: smallint
            nullable: true
        victory:
            type: smallint
            nullable: true
        deckLimit:
            type: smallint
            nullable: true
            column: deck_limit
        slot:
            type: string
            length: 50
            nullable: true
        stage:
            type: smallint
            nullable: true
        traits:
            type: string
            length: 255
            nullable: true
            gedmo:
                - translatable
        deckRequirements:
            type: string
            length: 255
            nullable: true
        deckOptions:
            type: string
            length: 255
            nullable: true
        restrictions:
            type: string
            length: 255
            nullable: true
        flavor:
            type: text
            nullable: true
            gedmo:
                - translatable
        illustrator:
            type: string
            length: 255
            nullable: true
        isUnique:
            type: boolean
            nullable: false
            column: is_unique
        doubleSided:
            type: boolean
            nullable: true
            column: double_sided
        backText:
            type: text
            nullable: true
            gedmo:
                - translatable
        backFlavor:
            type: text
            nullable: true
            gedmo:
                - translatable
        backName:
            type: string
            length: 1024
            nullable: true
            gedmo:
                - translatable
        octgnId:
            type: string
            nullable: true
            column: octgn_id
    uniqueConstraints:
        card_code_idx:
            columns: [ code ]
